# Generated by Django 2.0.1 on 2018-12-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181211_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='beli',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(0, '立减券'), (1, '满减券'), (2, '折扣券')], default=0, verbose_name='券类型'),
        ),
    ]
